import marimo

__generated_with = "0.20.2"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    import altair as alt
    import numpy as np
    import pandas as pd
    from pathlib import Path

    return Path, alt, mo, np, pd


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Inter-rater agreement for LLM judges

    Five condition types in this project are scored by a panel of three LLM judges
    (`gpt-5-nano`, `deepseek-chat`, `gemini-2.5-flash-lite`) with a majority-vote
    reducer: **persona**, **preference**, **variety**, **language**, and the
    code-style conditions (**style_python_javascript / style_javascript_python**).

    This notebook quantifies how much the judges actually agree, broken down by
    condition and model. The unit is one (sample, judge) row pulled from
    `judges.parquet` (generated by `just report protocol1/T0/dynamic`).

    Metrics:
    - **Fleiss' kappa** (3 raters, categorical: target / pattern / unknown)
    - **Pairwise Cohen's kappa** for each judge pair
    - **Per-judge marginal distribution** — bias diagnostic
    - **Unanimous rate** sanity-check against the stored metadata
    """)
    return


@app.cell
def _(Path, mo, pd):
    _root = Path(__file__).resolve().parent.parent.parent
    judges_path = _root / "outputs" / "viz" / "protocol1" / "T0" / "dynamic" / "judges.parquet"

    if not judges_path.exists():
        mo.stop(
            True,
            mo.md(
                f"**`{judges_path.relative_to(_root)}` not found.** "
                "Run `just report protocol1/T0/dynamic` first."
            ),
        )

    judges = pd.read_parquet(judges_path)
    judges
    return (judges,)


@app.cell(hide_code=True)
def _(judges, mo):
    mo.md(
        f"""
        **Loaded {len(judges):,} judge-rows.**

        - Samples: {judges['sample_id'].nunique():,}
        - Judges: {sorted(judges['judge_id'].unique())}
        - Conditions: {sorted(judges['condition'].unique())}
        - Models: {judges['model'].nunique()}
        """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"## 1. Per-judge marginal distribution")
    return


@app.cell
def _(alt, judges):
    _marg = (
        judges.groupby(["condition", "judge_id", "classification"])
        .size()
        .reset_index(name="n")
    )
    _marg["rate"] = _marg.groupby(["condition", "judge_id"])["n"].transform(
        lambda s: s / s.sum()
    )
    marginals = _marg

    marginals_chart = (
        alt.Chart(marginals)
        .mark_bar()
        .encode(
            x=alt.X("rate:Q", title="proportion", axis=alt.Axis(format=".0%")),
            y=alt.Y("judge_id:N", title=None),
            color=alt.Color(
                "classification:N",
                scale=alt.Scale(
                    domain=["target", "pattern", "unknown"],
                    range=["#4c78a8", "#f58518", "#bab0ac"],
                ),
            ),
            row=alt.Row("condition:N", title=None),
        )
        .properties(width=400, height=60)
    )
    marginals_chart
    return marginals, marginals_chart


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ## 2. Fleiss' kappa

        Built on a counts matrix where each row is a sample and each column is one of
        `{target, pattern, unknown}`. Cell value = number of judges that picked that
        class for that sample. `fleiss_kappa` requires exactly the same number of
        raters across rows.

        Interpretation rough guide: ≥ 0.81 almost perfect, 0.61–0.80 substantial,
        0.41–0.60 moderate, 0.21–0.40 fair, ≤ 0.20 slight.
        """
    )
    return


@app.cell
def _(np, pd):
    from statsmodels.stats.inter_rater import fleiss_kappa as _fleiss_kappa

    _CLASSES = ["target", "pattern", "unknown"]

    def _counts_matrix(df: pd.DataFrame) -> np.ndarray | None:
        """Build sample × class counts matrix from a long-form judge df."""
        pivot = (
            df.groupby(["sample_id", "classification"])
            .size()
            .unstack(fill_value=0)
            .reindex(columns=_CLASSES, fill_value=0)
        )
        if pivot.empty:
            return None
        row_totals = pivot.sum(axis=1)
        if row_totals.nunique() != 1:
            return None
        return pivot.to_numpy()

    def fleiss(df: pd.DataFrame) -> float | None:
        m = _counts_matrix(df)
        if m is None or len(m) < 2:
            return None
        try:
            return float(_fleiss_kappa(m))
        except Exception:
            return None

    return _CLASSES, _counts_matrix, fleiss


@app.cell
def _(fleiss, judges, pd):
    fleiss_overall = fleiss(judges)
    fleiss_by_condition = (
        judges.groupby("condition", group_keys=False)
        .apply(fleiss)
        .reset_index(name="fleiss_kappa")
        .sort_values("fleiss_kappa", ascending=False)
    )
    fleiss_by_condition_pair = (
        judges.groupby("condition_pair", group_keys=False)
        .apply(fleiss)
        .reset_index(name="fleiss_kappa")
        .sort_values("fleiss_kappa", ascending=False)
    )
    fleiss_by_model = (
        judges.groupby("model", group_keys=False)
        .apply(fleiss)
        .reset_index(name="fleiss_kappa")
        .sort_values("fleiss_kappa", ascending=False)
    )

    print(f"Overall Fleiss' kappa: {fleiss_overall:.3f}")
    pd.concat(
        {
            "by condition": fleiss_by_condition.set_index("condition"),
            "by condition_pair": fleiss_by_condition_pair.set_index("condition_pair"),
            "by model": fleiss_by_model.set_index("model"),
        }
    )
    return (
        fleiss_by_condition,
        fleiss_by_condition_pair,
        fleiss_by_model,
        fleiss_overall,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"## 3. Pairwise Cohen's kappa")
    return


@app.cell
def _(judges, pd):
    from itertools import combinations
    from sklearn.metrics import cohen_kappa_score

    def _pairwise(df: pd.DataFrame) -> pd.DataFrame:
        pivot = df.pivot_table(
            index="sample_id",
            columns="judge_id",
            values="classification",
            aggfunc="first",
        )
        pivot = pivot.dropna()
        judges_list = sorted(pivot.columns)
        rows = []
        for a, b in combinations(judges_list, 2):
            try:
                k = cohen_kappa_score(pivot[a], pivot[b])
            except Exception:
                k = None
            rows.append({"judge_a": a, "judge_b": b, "cohen_kappa": k, "n": len(pivot)})
        return pd.DataFrame(rows)

    pairwise_overall = _pairwise(judges)
    pairwise_by_condition = (
        judges.groupby("condition", group_keys=False)
        .apply(_pairwise)
        .reset_index(level=0)
    )

    pairwise_overall
    return cohen_kappa_score, pairwise_by_condition, pairwise_overall


@app.cell
def _(alt, pairwise_by_condition):
    pairwise_chart = (
        alt.Chart(pairwise_by_condition)
        .mark_rect()
        .encode(
            x=alt.X("judge_a:N", title=None),
            y=alt.Y("judge_b:N", title=None),
            color=alt.Color(
                "cohen_kappa:Q",
                scale=alt.Scale(domain=[-0.2, 1.0], scheme="viridis"),
            ),
            tooltip=["judge_a", "judge_b", "cohen_kappa", "n"],
            facet=alt.Facet("condition:N", columns=3, title=None),
        )
        .properties(width=120, height=120)
    )
    pairwise_chart
    return (pairwise_chart,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
        ## 4. Unanimous-rate sanity check

        The `unanimous` flag was stored at scoring time by `majority_vote_with_agreement`.
        Recompute it from per-judge classifications and compare — values should match
        exactly (modulo any logs scored before the multi-judge flag was added).
        """
    )
    return


@app.cell
def _(judges, pd):
    _recomputed = (
        judges.groupby("sample_id")["classification"]
        .apply(lambda s: s.nunique() == 1)
        .rename("unanimous_recomputed")
    )
    _stored = judges.groupby("sample_id")["unanimous"].first()
    unanimous_check = pd.concat([_stored, _recomputed], axis=1)
    unanimous_check["match"] = (
        unanimous_check["unanimous"].astype("boolean")
        == unanimous_check["unanimous_recomputed"]
    )
    print(f"Stored unanimous rate:     {_stored.mean():.3f}")
    print(f"Recomputed unanimous rate: {_recomputed.mean():.3f}")
    print(f"Per-sample match rate:     {unanimous_check['match'].mean():.3f}")
    unanimous_check.head()
    return (unanimous_check,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"## 5. Agreement vs n_turns")
    return


@app.cell
def _(alt, judges, pd):
    _per_sample = (
        judges.groupby(["model", "condition", "n_turns", "sample_id"])["unanimous"]
        .first()
        .reset_index()
    )
    _per_sample["n_turns_int"] = pd.to_numeric(_per_sample["n_turns"], errors="coerce")
    _traj = (
        _per_sample.groupby(["condition", "n_turns_int"])["unanimous"]
        .mean()
        .reset_index(name="unanimous_rate")
        .sort_values(["condition", "n_turns_int"])
    )

    agreement_traj_chart = (
        alt.Chart(_traj)
        .mark_line(point=True)
        .encode(
            x=alt.X("n_turns_int:Q", title="n_turns"),
            y=alt.Y(
                "unanimous_rate:Q",
                title="unanimous rate",
                scale=alt.Scale(domain=[0, 1]),
                axis=alt.Axis(format=".0%"),
            ),
            color=alt.Color("condition:N"),
        )
        .properties(width=500, height=300)
    )
    agreement_traj_chart
    return (agreement_traj_chart,)


if __name__ == "__main__":
    app.run()
