protocol: behavioral

conditions:
  - classify_sh_history
  - classify_mc_history

n_turns:
  - 1
  - 2
  - 3
  - 4
  - 6
  - 8
  - 11
  - 16
  - 22
  - 31
  - 43
  - 50

instruction_templates:
  - instruction_no_hint
n_trials: 3

