provider: openrouter

models:
  - google/gemini-2.5-flash
  - meta-llama/llama-3.3-70b-instruct
  - qwen/qwen3.5-plus-02-15
  - minimax/minimax-m2.5
  - moonshotai/kimi-k2.5
  - openai/gpt-5.2
  - google/gemini-3-flash-preview
  - google/gemini-2.5-pro
  # - google/gemini-3-pro-preview
  - meta-llama/llama-4-maverick
  - meta-llama/llama-4-scout
  - deepseek/deepseek-v3.2

provider_args:
  quantizations: ["fp16", "bf16", "unknown"]
